apiVersion: v1
kind: Service
metadata: # kpt-merge: example/base-app
  name: balancereader
  namespace: example
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|example|base-app'
spec:
  type: LoadBalancer
  selector:
    app: balancereader
  ports:
  - name: http
    port: 80
    targetPort: 8080
