apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: example/ledger-db-config
  name: ledger-db-config
  labels:
    app: transactionhistory
  namespace: transactionhistory-dev
  annotations:
    internal.kpt.dev/upstream-identifier: '|ConfigMap|example|ledger-db-config'
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: password
  SPRING_DATASOURCE_URL: jdbc:postgresql://ledger-db:5432/postgresdb
  SPRING_DATASOURCE_USERNAME: admin # should match POSTGRES_USER
  SPRING_DATASOURCE_PASSWORD: password # should match POSTGRES_PASSWORD
