apiVersion: v1
kind: ConfigMap
metadata:
  name: accounts-db-config
  namespace: example
  labels:
    app: userservice
data:
  POSTGRES_DB: db
  POSTGRES_USER: db-admin
  POSTGRES_PASSWORD: db-pwd
  ACCOUNTS_DB_URI: postgresql://db-admin:db-pwd@accounts-db:5432/db
#  ACCOUNTS_DB_URI: postgresql://db-admin:db-pwd@accounts-db.accounts-db-dev:5432/db