apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: example/accounts-db-config
  name: accounts-db-config
  namespace: userservice-dev
  labels:
    app: userservice
  annotations:
    internal.kpt.dev/upstream-identifier: '|ConfigMap|example|accounts-db-config'
data:
  POSTGRES_DB: accounts-db
  POSTGRES_USER: accounts-admin
  POSTGRES_PASSWORD: accounts-pwd
  ACCOUNTS_DB_URI: postgresql://accounts-admin:accounts-pwd@accounts-db:5432/accounts-db
