apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: example/environment-config
  name: environment-config
  namespace: userservice-dev
  labels:
    app: userservice
  annotations:
    internal.kpt.dev/upstream-identifier: '|ConfigMap|example|environment-config'
data:
  LOCAL_ROUTING_NUM: "883745000"
  PUB_KEY_PATH: /tmp/.ssh/publickey
