apiVersion: v1
kind: Service
metadata: # kpt-merge: example/base-db
  name: ledger-db
  labels:
    tier: db
    app: ledger-db
  namespace: example
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|example|base-db'
spec:
  ports:
    - port: 5432
      name: tcp
      targetPort: 5432
      protocol: TCP
  selector:
    tier: db
    app: ledger-db
