apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: example
data:
  POSTGRES_DB: db
  POSTGRES_USER: db-admin
  POSTGRES_PASSWORD: db-pwd
  ACCOUNTS_DB_URI: postgresql://db-admin:db-pwd@base-db:5432/base-db
