apiVersion: fn.kpt.dev/v1alpha1
kind: StarlarkRun
metadata:
  name: set-name
  annotations:
    config.kubernetes.io/local-config: "true"
  labels:
    app: base-db
source: |-
  def set_name(resources):
    pkgName = ""
    isAbstractPackage = False
    for resource in resources:
      if resource["kind"] == "ConfigMap" and resource["metadata"]["name"] == "kptfile.kpt.dev" and resource["data"]["name"] == "example":
        isAbstractPackage = True
      if resource["kind"] == "Kptfile":
        pkgName = resource["metadata"]["name"]
    if not isAbstractPackage:
      # update resource name only if this is an abstract blueprint
      return
    if pkgName == "":
      fail("package must have a name.")
      return

    for resource in ctx.resource_list["items"]:
      if resource["kind"] == "Service":
        resource["metadata"]["name"] = pkgName
      if resource["kind"] == "Deployment":
        resource["metadata"]["name"] = pkgName
  set_name(ctx.resource_list["items"])
